### ISSUE TITLE
About contibutions

### ISSUE THREAD

**Issue by JoseAlavez** [spotify/completable-futures#72]
Hi again :)!

I forgot to ask since the very beginning, if this repository is only in maintenance mode. When looking at the builds and maven repo, the latest release was almost 3 years ago.

I ask because as promised, I was planning to start the conversation to allow tasks to be cancelled when failing fast. 

To showcase why cancelling remaining tasks is important, the output of https://repl.it/@JoseAlavez/CancelCompletableFuturejava#Main.java can be handy. 

Will wait for the team reply, 

Best Regards,

**Comment by mbruggmann** [comment]
Hi @JoseAlavez. To be honest, I haven't spent any time on this project after the feature-set and APIs have settled a few years ago. But it would be nice to at least fix the CD pipelines, and get a release out with the recent improvements. Not sure about @dflemstr and @spkrka?

**Comment by mbruggmann** [comment]
If nothing else, I managed to get a new release out (v0.3.3).
